### ISSUE TITLE
How one can  be sure  that the instrumentation is loaded before?

### ISSUE THREAD

**Issue by bahcetepe** [invesdwin/invesdwin-instrument#14]
Hi,

you stated that "Make sure that the instrumentation is loaded before the classes of the aspects or the classes that use the aspects are loaded by the classloader. Only classes that get loaded after initializing load time weaving will be successfully woven by aspectj."

Is there a way to accomplish that?

Thanks in advance.

**Comment by subes** [comment]
Just make sure you don't import/access/instantiate any classes before calling the instrumentation initializer.

You can enable classloader debugging to find out which classes get loaded before the instrumentation. Or just add a breakpoint in the classloader and find out using the debugger.

**Comment by bahcetepe** [comment]
Thank you dude.

**Comment by bahcetepe** [comment]
Ah i forget to ask that, is there a trick to force instrumentation initializer run first? What to do if it runs after some of classes that need to be woven?

**Comment by subes** [comment]
The trick is written in the usage part of main README.md. Just call the instrumentation in a static initializer or before your application startup logic inside your main method.

Make sure the main class has no additional imports (or causes for eager loads of those) to classes that need to be woven.

If classes are not woven because they have been loaded too early, aspects will just not apply to them. Thus things like @Configurable won't work on those classes.
