### ISSUE TITLE
Refactor to not use sun.misc.unsafe

### ISSUE THREAD

**Issue by mojo2012** [invesdwin/invesdwin-instrument#6]
Hi,

first thanks for this great plugin. I forked you project and adapted it to my needs (saved me dozends of hours :-)).
But do you think there is a way to get rid of the `sun.misc.Unsafe` usages?

**Comment by subes** [comment]
Hi,

in Java 8 and prior yes, in Java 9 and upper sadly not. You can look at earlier revisions where URLClassLoader was modified via reflection. I switched to Unsafe so no command-line flags for unexpected reflectional access is used. If you want to use those command-line flags you can go with old solution maybe. Though I remember there were some other problems with the new implementation that replaced URLClassLoader.

**Comment by subes** [comment]
Essentially we need the URLClassLoader modification to extend the classloader for some classes we need in the agent.

**Comment by mojo2012** [comment]
Have you ever investigated creating a custom classloader that functionas as a new root parent CL? Something like the spring-devtools guys do. They restart the whole process with a new CL that has a lot more capabilities than the regular one. You could then add enable instrumentation there by default.

Btw, I opened a PR for java11 compatibility! Still relies on Unsafe though ... :-\

**Comment by subes** [comment]
Looks good, I merged it. I guess the variable name changed or why is the change neccessary?

I thought about creating such a CL, but did not pursue it since I have no usecase for myself. The current solution works fine for me. But the classloader might help in more complex scenarios, so I would be happy for a PR for such a feature.

Though the Classloader would be needed to be configured somewhere from the outside for the actual application and the application needs to support working in nested classloaders.

**Comment by subes** [comment]
I have modified the PR change a bit to be more upwards compatible (don't check against a specific version number) and make java9/10 support a fallback option since most users will either stick to java 8 or go directly to something above java 10.

https://github.com/subes/invesdwin-instrument/commit/ccedef3dd039433463ed05c5c5ae35fd7d9c4b09

**Comment by mojo2012** [comment]
Ok. It bugs me a bit that we still rely on `Unsafe` here - this will be removed in java 12 I think :-\

Btw I adapted this project even further by allowing it to register `ClassFileTransformer´s. You can look at the code here: https://github.com/spot-next/spot-framework/blob/develop/spot-instrumentation/src/main/java/io/spotnext/instrumentation/DynamicInstrumentationLoader.java

**Comment by subes** [comment]
With java 12, maybe an alternative to Unsafe will be provided. We will see. I will have a look later when I have more time, but maybe you are right and we have to move on to nested classloaders.

**Comment by subes** [comment]
Regarding the ClassFileTransformer, this is a change I would incorporate if you provide a pull-request. If there are more things you think might be helpful for others, feel free to make more suggestions. And thanks. :)

**Comment by subes** [comment]
Closing because Unsafe is still available in java 13.
